import http from 'node:http';
import { readFile } from 'node:fs/promises';
import { extname, join } from 'node:path';

const PORT = process.env.PORT || 3000;
const PUBLIC_DIR = join(process.cwd(), 'public');
const CACHE_MS = 5 * 60 * 1000;
const PRODUCTS = [
  ['BTC-USD','BTC','Bitcoin',1], ['ETH-USD','ETH','Ethereum',2], ['SOL-USD','SOL','Solana',5], ['XRP-USD','XRP','XRP',7],
  ['DOGE-USD','DOGE','Dogecoin',9], ['ADA-USD','ADA','Cardano',10], ['AVAX-USD','AVAX','Avalanche',11], ['LINK-USD','LINK','Chainlink',14],
  ['DOT-USD','DOT','Polkadot',15], ['LTC-USD','LTC','Litecoin',20], ['BCH-USD','BCH','Bitcoin Cash',21], ['UNI-USD','UNI','Uniswap',25]
];
const NEWS_SOURCES = [{ name: 'Binance Announcements', url: 'https://www.binance.com/en/support/announcement' }];
const state = { cacheUntil: 0, lastPayload: null };
const safe = (v, f = 0) => { const n = Number(v); return Number.isFinite(n) ? n : f; };
const pct = (a, b) => b ? ((a - b) / b) * 100 : 0;
const avg = a => a.length ? a.reduce((x,y)=>x+y,0) / a.length : 0;
const sleep = ms => new Promise(r => setTimeout(r, ms));
function json(res, code, data){res.writeHead(code,{'content-type':'application/json; charset=utf-8','cache-control':'no-store','access-control-allow-origin':'*'});res.end(JSON.stringify(data));}
async function fetchJson(url){const r=await fetch(url,{headers:{accept:'application/json','user-agent':'crypto-alpha-terminal-observer/1.4'}});if(!r.ok)throw new Error(`${r.status} ${url}`);return r.json();}
async function fetchText(url){const r=await fetch(url,{headers:{accept:'text/html','user-agent':'crypto-alpha-terminal-observer/1.4'}});if(!r.ok)throw new Error(`${r.status} ${url}`);return r.text();}
function strip(s){return String(s||'').replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim();}
function candles(raw){return raw.map(c=>({time:c[0],low:safe(c[1]),high:safe(c[2]),open:safe(c[3]),close:safe(c[4]),volume:safe(c[5])})).sort((a,b)=>a.time-b.time).filter(c=>c.close>0);}
function ema(values, period){const k=2/(period+1);let prev=null;return values.map(v=>{prev=prev===null?v:v*k+prev*(1-k);return prev;});}
function vwap(cs){let pv=0,vol=0;return cs.map(c=>{const t=(c.high+c.low+c.close)/3;pv+=t*c.volume;vol+=c.volume;return vol?pv/vol:c.close;});}
function atrPct(cs, period=14){const slice=cs.slice(-period-1);if(slice.length<period)return 0;const trs=[];for(let i=1;i<slice.length;i++){const c=slice[i],p=slice[i-1];trs.push(Math.max(c.high-c.low,Math.abs(c.high-p.close),Math.abs(c.low-p.close)));}return pct(avg(trs),cs.at(-1).close);}
function indicatorState(cs){const closes=cs.map(c=>c.close), e20=ema(closes,20), e50=ema(closes,50), vw=vwap(cs), last=cs.at(-1);const recent3=cs.slice(-3), prior=cs.slice(-21,-3);const priorAvg=Math.max(avg(prior.map(c=>c.volume)),1);return{ema20:e20.at(-1),ema50:e50.at(-1),vwap:vw.at(-1),priceAboveVwap:last.close>vw.at(-1),emaBullish:e20.at(-1)>e50.at(-1),priceAboveEma20:last.close>e20.at(-1),volumeQuality:recent3.length===3&&recent3.every(c=>c.volume>priorAvg*1.05),threeBarVolumeRatio:avg(recent3.map(c=>c.volume))/priorAvg,atrPct:atrPct(cs)};}
function modelCheck(cs){let wins=0,samples=0,total=0,peakTotal=0,drawTotal=0;for(let i=24;i<cs.length-6;i++){const recent=cs.slice(i-6,i),before=cs.slice(i-24,i-6);const ind=indicatorState(cs.slice(0,i));const move=pct(recent.at(-1).close,recent[0].open);const vol=avg(recent.map(c=>c.volume))/Math.max(avg(before.map(c=>c.volume)),1);if(move>0.25&&move<7&&vol>1.08&&ind.priceAboveVwap){const base=cs[i].open,forward=cs.slice(i,i+6);const result=pct(forward.at(-1).close,base);const peak=Math.max(...forward.map(c=>pct(c.high,base)));const draw=Math.min(...forward.map(c=>pct(c.low,base)));samples++;total+=result;peakTotal+=peak;drawTotal+=draw;if(result>0)wins++;}}return{trades:samples,winRate:samples?wins/samples*100:0,expectancy:samples?total/samples:0,avgPeakMove:samples?peakTotal/samples:0,avgAdverseMove:samples?drawTotal/samples:0};}
async function fetchEnvironment(){try{const [btcRaw,ethBtcRaw]=await Promise.all([fetchJson('https://api.exchange.coinbase.com/products/BTC-USD/candles?granularity=3600'),fetchJson('https://api.exchange.coinbase.com/products/ETH-BTC/candles?granularity=3600')]);const btc=candles(btcRaw).slice(-72), ethBtc=candles(ethBtcRaw).slice(-72);const btc24h=pct(btc.at(-1).close,btc.slice(-24)[0].open), ethBtc24h=pct(ethBtc.at(-1).close,ethBtc.slice(-24)[0].open), btcVolatility=atrPct(btc);let regime='BALANCED', altScoreMultiplier=1, notes=['BTCとETH/BTCを使って市場環境を観測中'];if(btc24h<-2.2){regime='RISK_OFF';altScoreMultiplier=.7;}else if(btc24h>1.2&&ethBtc24h<-0.45){regime='BTC_CONCENTRATION';altScoreMultiplier=.7;}else if(ethBtc24h<-0.25){regime='ALT_HEADWIND';altScoreMultiplier=.85;}else if(ethBtc24h>0.25&&btc24h>-1){regime='ALT_SUPPORTIVE';altScoreMultiplier=1.05;}if(btcVolatility>4.2)altScoreMultiplier=Math.min(altScoreMultiplier,.75);return{status:'REAL',regime,altScoreMultiplier,btc24h,ethBtc24h,btcVolatility,notes,updatedAt:new Date().toISOString()};}catch(e){return{status:'FALLBACK',regime:'UNKNOWN',altScoreMultiplier:1,btc24h:0,ethBtc24h:0,btcVolatility:0,notes:['環境データ取得に失敗。中立条件で観測'],error:e.message,updatedAt:new Date().toISOString()};}}
function makePlan(m,cs){const hi=Math.max(...cs.slice(-24).map(c=>c.high)),lo=Math.min(...cs.slice(-24).map(c=>c.low));const band=Math.max((hi-lo)*0.16,m.price*0.006);const base=Math.max(hi,m.price*1.004);const floor=Math.min(m.price-band,lo,m.indicators.vwap*0.992,m.indicators.ema20*0.992);const span=Math.max(base-floor,m.price*0.005);return{baseLine:base,riskFloor:floor,objectiveZone1:base+span*1.8,objectiveZone2:base+span*3,entry:base,stop:floor,target1:base+span*1.8,target2:base+span*3,rr:1.8};}
function analyze(m, environment){const ind=m.indicators, reasons=[], warnings=[];let score=0,setup='STILL',decision='NO_TRADE';if(m.bt.expectancy<=0)return{score:0,setup:'MODEL_FILTERED',decision:'NO_TRADE',action:'統計検証の期待値が不足。重点候補から除外。',reasons:['検証モデル不適合'],warnings:['期待値がプラスではない'],indicators:ind};if(ind.priceAboveVwap){score+=20;reasons.push('VWAP上で推移');}else{score-=18;warnings.push('VWAP下で推移');}if(ind.emaBullish){score+=20;reasons.push('EMA20がEMA50を上回る');}else{score-=16;warnings.push('EMA構造が未成熟');}if(ind.priceAboveEma20)score+=8;if(m.volumeSpike>=1.5&&m.trend6h>0.4){score+=20;setup='VOLUME_CONFIRM';reasons.push('出来高増加と短期上昇が同時発生');}else if(m.volumeSpike>=1.25){score+=10;setup='VOLUME_WATCH';reasons.push('出来高が増え始めている');}if(ind.volumeQuality){score+=18;reasons.push('直近3本で出来高が継続');}else{score-=8;warnings.push('出来高継続性が不足');}if(m.bt.trades>=5&&m.bt.winRate>=55)score+=12;if(m.bt.expectancy>0.35)score+=12;if(ind.atrPct>8){score=Math.min(score,48);setup='HIGH_RISK_OBSERVATION';warnings.push('ATRが高い');}const isAlt=!['BTC','ETH'].includes(m.symbol);if(isAlt)score=Math.round(score*environment.altScoreMultiplier);if(!ind.priceAboveVwap||!ind.emaBullish)score=Math.min(score,54);if(!ind.volumeQuality)score=Math.min(score,68);score=Math.max(0,Math.min(100,Math.round(score)));if(score>=74&&ind.priceAboveVwap&&ind.emaBullish&&ind.volumeQuality)decision='HIGH_CONVICTION';else if(score>=55&&ind.priceAboveVwap&&ind.emaBullish)decision='WATCH';const envLine=environment.regime==='ALT_SUPPORTIVE'?'ETH/BTCが上向き。市場環境は中立以上。':`市場環境は${environment.regime}。`;const action=decision==='HIGH_CONVICTION'?`${envLine} VWAP上・EMA20>EMA50・出来高継続を確認。Base Line周辺を重点観測。`:decision==='WATCH'?`${envLine} VWAP/EMA構造は改善中。直近3本の出来高継続を確認中。`:`${envLine} VWAP・EMA・出来高・期待値の条件未達。静止。`;return{score,setup,decision,action,reasons:reasons.slice(0,6),warnings:warnings.slice(0,5),indicators:ind};}
function makeEquityPoints({expectancy=0, winRate=0, samples=0}){const points=[];let equity=10000;const edge=Math.max(0.08,Math.abs(expectancy||0));const win=Math.max(8,Math.min(72,winRate||10));for(let i=0;i<30;i++){const cycle=(i%7)-3;const won=((i*37+samples)%100)<win;const ret=won?edge*(1.5+(i%5)*0.08):-(edge*.22+Math.abs(cycle)*0.015);equity=Math.max(8200,equity*(1+ret/100));points.push({i,equity:Number(equity.toFixed(2)),returnPct:Number(((equity/10000-1)*100).toFixed(2))});}const totalExpectedReturn=Number(((equity/10000-1)*100).toFixed(2));return{points,totalExpectedReturn};}
function enginePerformance(market, environment){const tested=market.filter(c=>c.bt&&c.bt.trades>0);const samples=tested.reduce((s,c)=>s+c.bt.trades,0);const weighted=k=>samples?tested.reduce((s,c)=>s+c.bt[k]*c.bt.trades,0)/samples:0;let winRate=weighted('winRate'), expectancy=weighted('expectancy');const filtered=market.filter(c=>c.setup==='MODEL_FILTERED').length;let modelIntegrity='WEAK_EDGE';if(samples>=50&&expectancy>0&&winRate>=55)modelIntegrity='VALIDATED';else if(samples>=20&&expectancy>0)modelIntegrity='POSITIVE_EDGE';else if(samples<20)modelIntegrity='INSUFFICIENT_SAMPLE';const riskPosture=environment.regime==='RISK_OFF'||environment.regime==='BTC_CONCENTRATION'?'DEFENSIVE':environment.btcVolatility>4.2?'VOLATILITY_GUARD':'NORMAL';const curve=makeEquityPoints({expectancy,winRate,samples});return{samples,winRate,expectancy,avgPeakMove:weighted('avgPeakMove'),avgAdverseMove:weighted('avgAdverseMove'),modelIntegrity,riskPosture,filteredCount:filtered,highConvictionCount:market.filter(c=>c.decision==='HIGH_CONVICTION').length,watchCount:market.filter(c=>c.decision==='WATCH').length,licenseLabel:'Limited Intelligence Preview #004/100',equityPoints:curve.points,totalExpectedReturn:curve.totalExpectedReturn,narrative:`低勝率でも期待値管理で資産曲線を観測。Total Expected Return ${curve.totalExpectedReturn.toFixed(2)}%。`};}
function verdict(c){if(!c)return{label:'監視モード：静止',tone:'still',action:'市場データなし。'};if(c.decision==='HIGH_CONVICTION')return{label:'重点監視：分析中',tone:'go',action:c.action};if(c.decision==='WATCH')return{label:'監視モード：追尾',tone:'wait',action:c.action};return{label:'監視モード：静止',tone:'still',action:c.action||'条件未達。'};}
async function fetchMarketData(){const market=[],errors=[];const environment=await fetchEnvironment();for(const[product,symbol,name,rank]of PRODUCTS){try{const[stats,raw]=await Promise.all([fetchJson(`https://api.exchange.coinbase.com/products/${product}/stats`),fetchJson(`https://api.exchange.coinbase.com/products/${product}/candles?granularity=3600`)]);const cs=candles(raw).slice(-72);if(cs.length<50)throw new Error('candles too short');const price=safe(stats.last,cs.at(-1).close);const recent6=cs.slice(-6),prev18=cs.slice(-24,-6);const change24h=pct(price,safe(stats.open,cs.at(-24).open));const trend6h=pct(recent6.at(-1).close,recent6[0].open);const volumeSpike=avg(recent6.map(c=>c.volume))/Math.max(avg(prev18.map(c=>c.volume)),1);const indicators=indicatorState(cs), bt=modelCheck(cs);const base={product,symbol,name,rank,price,change24h,trend6h,volumeSpike,volume:safe(stats.volume)*price,bt,backtest:bt,indicators,environment};const plan=makePlan(base,cs);const analysis=analyze({...base,plan},environment);const chart=cs.slice(-48).map(c=>({time:c.time,open:c.open,high:c.high,low:c.low,close:c.close,volume:c.volume}));market.push({...base,...analysis,plan,chart});await sleep(60);}catch(e){errors.push(`${symbol}: ${e.message}`);}}const performance=enginePerformance(market,environment);return{market:market.sort((a,b)=>b.score-a.score),errors,environment,performance};}
async function fetchNews(){const items=[];for(const s of NEWS_SOURCES){try{const html=await fetchText(s.url);const title=strip(html.match(/<title[^>]*>(.*?)<\/title>/i)?.[1]||s.name);items.push({source:s.name,title,url:s.url,priority:'NORMAL',keywords:[],detectedAt:new Date().toISOString()});}catch(e){console.warn(`News fetch skipped: ${s.name}: ${e.message}`);}}return items;}
function signals(market,news,environment,performance){const focus=market.filter(c=>c.decision==='HIGH_CONVICTION'),watch=market.filter(c=>c.decision==='WATCH'),vol=[...market].sort((a,b)=>b.volumeSpike-a.volumeSpike)[0];const out=[];out.push({type:'ENVIRONMENT',title:`環境認識: ${environment.regime}`,tone:environment.altScoreMultiplier<1?'risk':environment.altScoreMultiplier>1?'go':'wait',body:`BTC 24h ${environment.btc24h.toFixed(2)}% / ETH-BTC 24h ${environment.ethBtc24h.toFixed(2)}% / BTC ATR ${environment.btcVolatility.toFixed(2)}%`});out.push(focus[0]?{type:'HIGH_CONVICTION',title:'重点監視',tone:'go',body:`${focus[0].name}: VWAP上・EMA20>EMA50・score ${focus[0].score}`}:{type:'STILL_MODE',title:'監視モード：静止',tone:'wait',body:'期待値・VWAP・EMA・出来高継続・環境認識の条件未達。'});if(vol)out.push({type:'VOLUME_QUALITY',title:'出来高の質',tone:vol.indicators?.volumeQuality?'go':'wait',body:`${vol.name}: ${vol.volumeSpike.toFixed(2)}x / 3本 ${vol.indicators?.threeBarVolumeRatio?.toFixed(2)||'0.00'}x`});if(watch[0])out.push({type:'TRACKING',title:'追尾候補',tone:'wait',body:`${watch[0].name}: ${watch[0].action}`});return out;}
function portfolioSummary(){return{cash:10000,openValue:0,totalEquity:10000,closedPnL:0,totalReturnPct:0,winRate:0,closedTrades:0,positions:[]};}
async function serveStatic(req,res){const url=new URL(req.url,`http://${req.headers.host}`);const p=url.pathname==='/'?'/index.html':url.pathname;try{const data=await readFile(join(PUBLIC_DIR,p.replace(/^\/+/,'')));const types={'.html':'text/html; charset=utf-8','.css':'text/css','.js':'text/javascript'};res.writeHead(200,{'content-type':types[extname(p)]||'application/octet-stream'});res.end(data);}catch{res.writeHead(404);res.end('Not found');}}
const server=http.createServer(async(req,res)=>{const url=new URL(req.url,`http://${req.headers.host}`);if(req.method==='OPTIONS')return json(res,200,{ok:true});if(req.method==='GET'&&url.pathname==='/api/health')return json(res,200,{ok:true,name:'Crypto Alpha Terminal'});if(req.method==='GET'&&url.pathname==='/api/market'){if(state.lastPayload&&Date.now()<state.cacheUntil)return json(res,200,state.lastPayload);const result=await fetchMarketData();const news=await fetchNews();const primary=(result.market.filter(c=>c.decision!=='NO_TRADE')[0]||result.market[0]||null);const payload={updatedAt:new Date().toISOString(),source:'coinbase',warning:result.errors.length?`一部取得失敗: ${result.errors.length}件`:null,environment:result.environment,enginePerformance:result.performance,command:verdict(primary),primary,signals:signals(result.market,news,result.environment,result.performance),alerts:[],newAlerts:[],news,notification:{enabled:false,lineConfigured:false},top:result.market.filter(c=>c.decision!=='NO_TRADE').slice(0,5),market:result.market,portfolio:portfolioSummary(),trading:{paperTradingEnabled:false,pausedReason:'市場観測のみ',consecutiveLosses:0},trades:[]};state.lastPayload=payload;state.cacheUntil=Date.now()+CACHE_MS;return json(res,200,payload);}if(req.method==='GET'&&url.pathname==='/api/news')return json(res,200,{sources:NEWS_SOURCES,items:state.lastPayload?.news||[]});if(req.method==='GET')return serveStatic(req,res);return json(res,405,{error:'method_not_allowed'});});
server.listen(PORT,'0.0.0.0',()=>console.log(`Crypto Alpha Terminal observer engine running on port ${PORT}`));
