import http from 'node:http';
import { readFile } from 'node:fs/promises';
import { extname, join } from 'node:path';

const PORT = process.env.PORT || 3000;
const PUBLIC_DIR = join(process.cwd(), 'public');
const CACHE_MS = 5 * 60 * 1000;
const PRODUCTS = [
  ['BTC-USD','BTC','Bitcoin',1], ['ETH-USD','ETH','Ethereum',2], ['SOL-USD','SOL','Solana',5], ['XRP-USD','XRP','XRP',7],
  ['DOGE-USD','DOGE','Dogecoin',9], ['ADA-USD','ADA','Cardano',10], ['AVAX-USD','AVAX','Avalanche',11], ['LINK-USD','LINK','Chainlink',14],
  ['DOT-USD','DOT','Polkadot',15], ['LTC-USD','LTC','Litecoin',20], ['BCH-USD','BCH','Bitcoin Cash',21], ['UNI-USD','UNI','Uniswap',25]
];
const NEWS_SOURCES = [{ name: 'Binance Announcements', url: 'https://www.binance.com/en/support/announcement' }];
const state = { cacheUntil: 0, lastMarket: [], lastNews: [], lastEnvironment: null, alerts: [], lastUpdated: null };
const safe = (v, f = 0) => { const n = Number(v); return Number.isFinite(n) ? n : f; };
const pct = (a, b) => b ? ((a - b) / b) * 100 : 0;
const avg = a => a.length ? a.reduce((x,y)=>x+y,0) / a.length : 0;
const sleep = ms => new Promise(r => setTimeout(r, ms));
function json(res, code, data){res.writeHead(code,{'content-type':'application/json; charset=utf-8','cache-control':'no-store','access-control-allow-origin':'*'});res.end(JSON.stringify(data));}
async function fetchJson(url){const r=await fetch(url,{headers:{accept:'application/json','user-agent':'crypto-alpha-terminal-observer/1.1'}});if(!r.ok)throw new Error(`${r.status} ${url}`);return r.json();}
async function fetchText(url){const r=await fetch(url,{headers:{accept:'text/html','user-agent':'crypto-alpha-terminal-observer/1.1'}});if(!r.ok)throw new Error(`${r.status} ${url}`);return r.text();}
function strip(s){return String(s||'').replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim();}
function candles(raw){return raw.map(c=>({time:c[0],low:safe(c[1]),high:safe(c[2]),open:safe(c[3]),close:safe(c[4]),volume:safe(c[5])})).sort((a,b)=>a.time-b.time).filter(c=>c.close>0);}
function ema(values, period){const k=2/(period+1);let prev=null;return values.map(v=>{prev=prev===null?v:v*k+prev*(1-k);return prev;});}
function vwap(cs){let pv=0,vol=0;return cs.map(c=>{const typical=(c.high+c.low+c.close)/3;pv+=typical*c.volume;vol+=c.volume;return vol?pv/vol:c.close;});}
function atrPct(cs, period=14){const slice=cs.slice(-period-1);if(slice.length<period)return 0;const trs=[];for(let i=1;i<slice.length;i++){const c=slice[i],p=slice[i-1];trs.push(Math.max(c.high-c.low,Math.abs(c.high-p.close),Math.abs(c.low-p.close)));}return pct(avg(trs),cs.at(-1).close);}
function indicatorState(cs){const closes=cs.map(c=>c.close);const e20=ema(closes,20);const e50=ema(closes,50);const vw=vwap(cs);const last=cs.at(-1);const recent3=cs.slice(-3);const prior18=cs.slice(-21,-3);const priorAvg=Math.max(avg(prior18.map(c=>c.volume)),1);return{ema20:e20.at(-1),ema50:e50.at(-1),vwap:vw.at(-1),priceAboveVwap:last.close>vw.at(-1),emaBullish:e20.at(-1)>e50.at(-1),priceAboveEma20:last.close>e20.at(-1),volumeQuality:recent3.length===3&&recent3.every(c=>c.volume>priorAvg*1.05),threeBarVolumeRatio:avg(recent3.map(c=>c.volume))/priorAvg,atrPct:atrPct(cs)};}
function modelCheck(cs){let wins=0,samples=0,total=0;for(let i=24;i<cs.length-6;i++){const recent=cs.slice(i-6,i),before=cs.slice(i-24,i-6);const ind=indicatorState(cs.slice(0,i));const move=pct(recent.at(-1).close,recent[0].open);const vol=avg(recent.map(c=>c.volume))/Math.max(avg(before.map(c=>c.volume)),1);if(move>0.4&&move<6&&vol>1.15&&ind.priceAboveVwap&&ind.emaBullish){const base=cs[i].open,end=cs.slice(i,i+6).at(-1).close;const result=pct(end,base);samples++;total+=result;if(result>0)wins++;}}return{trades:samples,winRate:samples?wins/samples*100:0,expectancy:samples?total/samples:0};}
async function fetchEnvironment(){try{const [btcRaw,ethBtcRaw]=await Promise.all([fetchJson('https://api.exchange.coinbase.com/products/BTC-USD/candles?granularity=3600'),fetchJson('https://api.exchange.coinbase.com/products/ETH-BTC/candles?granularity=3600')]);const btc=candles(btcRaw).slice(-72);const ethBtc=candles(ethBtcRaw).slice(-72);const btcLast=btc.at(-1);const ethBtcLast=ethBtc.at(-1);const btc6h=pct(btcLast.close,btc.slice(-6)[0].open);const btc24h=pct(btcLast.close,btc.slice(-24)[0].open);const ethBtc6h=pct(ethBtcLast.close,ethBtc.slice(-6)[0].open);const ethBtc24h=pct(ethBtcLast.close,ethBtc.slice(-24)[0].open);const btcVolatility=atrPct(btc);let regime='BALANCED';let altScoreMultiplier=1;let notes=['BTCとETH/BTCを使って市場環境を観測中'];if(btc24h<-2.2){regime='RISK_OFF';altScoreMultiplier=.7;notes.push('BTC下落圧が強く、広範囲の観測を厳格化');}else if(btc24h>1.2&&ethBtc24h<-0.45){regime='BTC_CONCENTRATION';altScoreMultiplier=.7;notes.push('BTC優位の資金集中を検知。アルト観測を厳格化');}else if(ethBtc24h<-0.25){regime='ALT_HEADWIND';altScoreMultiplier=.85;notes.push('ETH/BTC低下によりアルト環境をやや厳格化');}else if(ethBtc24h>0.25&&btc24h>-1){regime='ALT_SUPPORTIVE';altScoreMultiplier=1.05;notes.push('ETH/BTCが上向き。アルト環境は中立以上');}if(btcVolatility>4.2){altScoreMultiplier=Math.min(altScoreMultiplier,.75);notes.push('BTCボラティリティが高く、観測基準を引き締め');}return{status:'REAL',regime,altScoreMultiplier,btc6h,btc24h,ethBtc6h,ethBtc24h,btcVolatility,notes,updatedAt:new Date().toISOString()};}catch(e){return{status:'FALLBACK',regime:'UNKNOWN',altScoreMultiplier:1,btc6h:0,btc24h:0,ethBtc6h:0,ethBtc24h:0,btcVolatility:0,notes:['環境データ取得に失敗。中立条件で観測'],error:e.message,updatedAt:new Date().toISOString()};}}
function makePlan(m,cs){const highs=cs.slice(-24).map(c=>c.high),lows=cs.slice(-24).map(c=>c.low);const hi=Math.max(...highs),lo=Math.min(...lows);const band=Math.max((hi-lo)*0.16,m.price*0.006);const baseline=Math.max(hi,m.price*1.004);const floor=Math.min(m.price-band,lo,m.indicators.vwap*0.992,m.indicators.ema20*0.992);const span=Math.max(baseline-floor,m.price*0.005);return{entry:baseline,stop:floor,target1:baseline+span*1.8,target2:baseline+span*3,invalid:floor,rr:1.8,recentHigh:hi,recentLow:lo,baseLine:baseline,riskFloor:floor,objectiveZone1:baseline+span*1.8,objectiveZone2:baseline+span*3};}
function analyze(m, environment){const ind=m.indicators;const reasons=[];const warnings=[];let score=0,setup='STILL',decision='NO_TRADE';if(m.bt.expectancy<=0){return{score:0,setup:'MODEL_FILTERED',decision:'NO_TRADE',action:'統計検証の期待値が不足。重点候補から除外。',reasons:['検証モデル不適合'],warnings:['期待値がプラスではない'],indicators:ind,environmentalNotes:environment.notes};}if(ind.priceAboveVwap){score+=20;reasons.push('VWAP上で推移');}else{score-=18;warnings.push('VWAP下で推移');}if(ind.emaBullish){score+=20;reasons.push('EMA20がEMA50を上回る');}else{score-=16;warnings.push('EMA構造が未成熟');}if(ind.priceAboveEma20){score+=8;reasons.push('EMA20上で推移');}if(m.volumeSpike>=1.5&&m.trend6h>0.4){score+=20;setup='VOLUME_CONFIRM';reasons.push('出来高増加と短期上昇が同時発生');}else if(m.volumeSpike>=1.25){score+=10;setup='VOLUME_WATCH';reasons.push('出来高が増え始めている');}if(ind.volumeQuality){score+=18;reasons.push('直近3本で出来高が継続');}else{score-=8;warnings.push('出来高継続性が不足');}if(m.bt.trades>=5&&m.bt.winRate>=55){score+=12;reasons.push('検証勝率が55%以上');}if(m.bt.expectancy>0.35){score+=12;reasons.push('検証期待値がプラス');}if(ind.atrPct>8){score=Math.min(score,48);setup='HIGH_RISK_OBSERVATION';warnings.push('ATRが高く、観測レンジが拡大');}else if(ind.atrPct>5){score=Math.min(score,62);warnings.push('ボラティリティが高め');}const isAlt=!['BTC','ETH'].includes(m.symbol);if(isAlt&&environment.altScoreMultiplier<1){score=Math.round(score*environment.altScoreMultiplier);warnings.push(`市場環境フィルター: ${environment.regime}`);}if(isAlt&&environment.altScoreMultiplier>1){score=Math.round(score*environment.altScoreMultiplier);reasons.push('ETH/BTC環境が中立以上');}if(!ind.priceAboveVwap||!ind.emaBullish)score=Math.min(score,54);if(!ind.volumeQuality)score=Math.min(score,68);score=Math.max(0,Math.min(100,Math.round(score)));if(score>=74&&ind.priceAboveVwap&&ind.emaBullish&&ind.volumeQuality&&ind.atrPct<=5.5)decision='HIGH_CONVICTION';else if(score>=55&&ind.priceAboveVwap&&ind.emaBullish&&ind.atrPct<=8)decision='WATCH';const envLine=isAlt&&environment.altScoreMultiplier<1?`市場環境は${environment.regime}。アルト観測を厳格化。`:environment.regime==='ALT_SUPPORTIVE'?`ETH/BTCが上向き。市場環境は中立以上。`:`市場環境は${environment.regime}。`;const action=decision==='HIGH_CONVICTION'?`${envLine} VWAP上・EMA20>EMA50・出来高継続を確認。Base Line ${m.plan.baseLine.toFixed(m.price<1?5:2)}周辺を重点観測。`:decision==='WATCH'?`${envLine} VWAP/EMA構造は改善中。直近3本の出来高継続を確認中。`:`${envLine} VWAP・EMA・出来高・期待値の条件未達。静止。`;return{score,setup,decision,action,reasons:reasons.slice(0,6),warnings:warnings.slice(0,5),indicators:ind,environmentalNotes:environment.notes};}
function verdict(c){if(!c)return{label:'監視モード：静止',tone:'still',action:'市場データなし。'};if(c.decision==='HIGH_CONVICTION')return{label:'重点監視：分析中',tone:'go',action:c.action};if(c.decision==='WATCH')return{label:'監視モード：追尾',tone:'wait',action:c.action};return{label:'監視モード：静止',tone:'still',action:c.action||'条件未達。'};}
async function fetchMarketData(){const market=[],errors=[];const environment=await fetchEnvironment();for(const[product,symbol,name,rank]of PRODUCTS){try{const[stats,raw]=await Promise.all([fetchJson(`https://api.exchange.coinbase.com/products/${product}/stats`),fetchJson(`https://api.exchange.coinbase.com/products/${product}/candles?granularity=3600`)]);const cs=candles(raw).slice(-72);if(cs.length<50)throw new Error('candles too short');const price=safe(stats.last,cs.at(-1).close);const recent6=cs.slice(-6),prev18=cs.slice(-24,-6);const change24h=pct(price,safe(stats.open,cs.at(-24).open));const trend6h=pct(recent6.at(-1).close,recent6[0].open);const volumeSpike=avg(recent6.map(c=>c.volume))/Math.max(avg(prev18.map(c=>c.volume)),1);const indicators=indicatorState(cs);const bt=modelCheck(cs);const base={product,symbol,name,rank,price,change24h,trend6h,volumeSpike,volume:safe(stats.volume)*price,bt,backtest:bt,indicators,environment};const plan=makePlan(base,cs);const analysis=analyze({...base,plan},environment);const chart=cs.slice(-48).map(c=>({time:c.time,open:c.open,high:c.high,low:c.low,close:c.close,volume:c.volume}));market.push({...base,...analysis,plan,chart});await sleep(60);}catch(e){errors.push(`${symbol}: ${e.message}`);}}state.lastEnvironment=environment;return{market:market.sort((a,b)=>b.score-a.score),errors,environment};}
async function fetchNews(){const items=[];for(const s of NEWS_SOURCES){try{const html=await fetchText(s.url);const title=strip(html.match(/<title[^>]*>(.*?)<\/title>/i)?.[1]||s.name);items.push({source:s.name,title,url:s.url,priority:'NORMAL',keywords:[],detectedAt:new Date().toISOString()});}catch(e){console.warn(`News fetch skipped: ${s.name}: ${e.message}`);}}state.lastNews=items;return items;}
function signals(market,news,environment){const focus=market.filter(c=>c.decision==='HIGH_CONVICTION'),watch=market.filter(c=>c.decision==='WATCH'),vol=[...market].sort((a,b)=>b.volumeSpike-a.volumeSpike)[0],out=[];out.push({type:'ENVIRONMENT',title:`環境認識: ${environment.regime}`,tone:environment.altScoreMultiplier<1?'risk':environment.altScoreMultiplier>1?'go':'wait',body:`BTC 24h ${environment.btc24h.toFixed(2)}% / ETH-BTC 24h ${environment.ethBtc24h.toFixed(2)}% / BTC ATR ${environment.btcVolatility.toFixed(2)}%`});if(focus[0])out.push({type:'HIGH_CONVICTION',title:'重点監視',tone:'go',body:`${focus[0].name}: VWAP上・EMA20>EMA50・score ${focus[0].score}`});else out.push({type:'STILL_MODE',title:'監視モード：静止',tone:'wait',body:'期待値・VWAP・EMA・出来高継続・環境認識の条件未達。'});if(vol)out.push({type:'VOLUME_QUALITY',title:'出来高の質',tone:vol.indicators?.volumeQuality?'go':'wait',body:`${vol.name}: ${vol.volumeSpike.toFixed(2)}x / 3本 ${vol.indicators?.threeBarVolumeRatio?.toFixed(2)||'0.00'}x`});if(watch[0])out.push({type:'TRACKING',title:'追尾候補',tone:'wait',body:`${watch[0].name}: ${watch[0].action}`});return out;}
function portfolioSummary(){return{cash:10000,openValue:0,totalEquity:10000,closedPnL:0,totalReturnPct:0,winRate:0,closedTrades:0,positions:[]};}
async function serveStatic(req,res){const url=new URL(req.url,`http://${req.headers.host}`);const p=url.pathname==='/'?'/index.html':url.pathname;const filePath=join(PUBLIC_DIR,p.replace(/^\/+/,''));try{const data=await readFile(filePath);const types={'.html':'text/html; charset=utf-8','.css':'text/css','.js':'text/javascript'};res.writeHead(200,{'content-type':types[extname(filePath)]||'application/octet-stream'});res.end(data);}catch{res.writeHead(404);res.end('Not found');}}
const server=http.createServer(async(req,res)=>{const url=new URL(req.url,`http://${req.headers.host}`);if(req.method==='OPTIONS')return json(res,200,{ok:true});if(req.method==='GET'&&url.pathname==='/api/health')return json(res,200,{ok:true,name:'Crypto Alpha Terminal'});if(req.method==='GET'&&url.pathname==='/api/market'){let result,news;if(state.lastMarket.length&&Date.now()<state.cacheUntil){result={market:state.lastMarket,errors:[],environment:state.lastEnvironment||{status:'CACHE',regime:'UNKNOWN',altScoreMultiplier:1,btc6h:0,btc24h:0,ethBtc6h:0,ethBtc24h:0,btcVolatility:0,notes:['cache']}};news=state.lastNews;}else{result=await fetchMarketData();news=await fetchNews();state.lastMarket=result.market;state.cacheUntil=Date.now()+CACHE_MS;}state.lastUpdated=new Date().toISOString();const sig=signals(result.market,news,result.environment);const actionables=result.market.filter(c=>c.decision!=='NO_TRADE').slice(0,5);const primary=(actionables[0]||result.market[0]||null);const command=verdict(primary);return json(res,200,{updatedAt:state.lastUpdated,source:'coinbase',warning:result.errors.length?`一部取得失敗: ${result.errors.length}件`:null,environment:result.environment,command,primary,signals:sig,alerts:state.alerts.slice(0,20),newAlerts:[],news,notification:{enabled:false,lineConfigured:false},top:actionables,market:result.market,portfolio:portfolioSummary(),trading:{paperTradingEnabled:false,pausedReason:'市場観測のみ',consecutiveLosses:0},trades:[]});}if(req.method==='GET'&&url.pathname==='/api/news')return json(res,200,{sources:NEWS_SOURCES,items:state.lastNews});if(req.method==='GET')return serveStatic(req,res);return json(res,405,{error:'method_not_allowed'});});
server.listen(PORT,'0.0.0.0',()=>console.log(`Crypto Alpha Terminal observer engine running on port ${PORT}`));
